spring.application.name=KinalApp

spring.datasource.url=jdbc:mysql://localhost:3306/dbclientes_in5am?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Guatemala&allowPublicKeyRetrieval=true
spring.datasource.username=IN4AM
spring.datasource.password=Kinal@2025AM
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

server.port=8083

logging.level.com.estebanruano.kinalapp=DEBUG
